package com.freetuition.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;



//@Entity marks this class as an entity, 
//meaning that we intend to map this class to a table in our database.
 
@Entity
@Table(name = "request", schema="freetuition")

public class Request {
	
	//The @Id annotation denotes that we wish to use this field as a primary key on this table.
	@Id
	//The @Column annotation denotes that we want this field to represent a column on our table.
	
	@Column(name = "req_id")
	/*
	 * The @GeneratedValue annotation specifies that the value of the data in
	 * this column is generated by a sequence. For example, the serial data
	 * type in Postgres has an underlying sequence which is used to generate
	 * the next value which should be inserted on our table in this column.
	 */
	@GeneratedValue(generator = "req_id_seq", strategy = GenerationType.AUTO)
	@SequenceGenerator(allocationSize = 1, name = "req_id_seq", sequenceName = "req_id_seq")
	private int request_id;
	@Column
	private int employee_id;
	@Column
	private String school;
	@Column
	private String course;
	@Column
	private String type;
	@Column
	private double price;
	@Column
	private String status;
	@Column
	private Date graduation;
	@Column
	private String receipt;
	@Column
	private Date date;
	
	public Request( ) {}

	public Request(int request_id, int employee_id, String school, String course, String type, double price,
			String status, Date graduation, String receipt, Date date) {
		super();
		this.request_id = request_id;
		this.employee_id = employee_id;
		this.school = school;
		this.course = course;
		this.type = type;
		this.price = price;
		this.status = status;
		this.graduation = graduation;
		this.receipt = receipt;
		this.date = date;
	}

	public int getRequest_id() {
		return request_id;
	}

	public void setRequest_id(int request_id) {
		this.request_id = request_id;
	}

	public int getEmployee_id() {
		return employee_id;
	}

	public void setEmployee_id(int employee_id) {
		this.employee_id = employee_id;
	}

	public String getSchool() {
		return school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	public String getCourse() {
		return course;
	}

	public void setCourse(String course) {
		this.course = course;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getGraduation() {
		return graduation;
	}

	public void setGraduation(Date graduation) {
		this.graduation = graduation;
	}

	public String getReceipt() {
		return receipt;
	}

	public void setReceipt(String receipt) {
		this.receipt = receipt;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Override
	public String toString() {
		return "Request [request_id=" + request_id + ", employee_id=" + employee_id + ", school=" + school + ", course="
				+ course + ", type=" + type + ", price=" + price + ", status=" + status + ", graduation=" + graduation
				+ ", receipt=" + receipt + ", date=" + date + "]";
	}

	
	

}
