package com.freetuition.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;



//@Entity marks this class as an entity, 
//meaning that we intend to map this class to a table in our database.
 
@Entity
@Table(name = "request", schema="freetuition")

public class Request {
	
	//The @Id annotation denotes that we wish to use this field as a primary key on this table.
	@Id
	//The @Column annotation denotes that we want this field to represent a column on our table.
	
	@Column(name = "request_id")
	/*
	 * The @GeneratedValue annotation specifies that the value of the data in
	 * this column is generated by a sequence. For example, the serial data
	 * type in Postgres has an underlying sequence which is used to generate
	 * the next value which should be inserted on our table in this column.
	 */
	@GeneratedValue(generator = "request_id_seq", strategy = GenerationType.AUTO)
	@SequenceGenerator(allocationSize = 1, name = "request_id_seq", sequenceName = "request_id_seq")
	private int requestId;
	@Column
	private int employeeId;
	@Column
	private String school;
	@Column
	private String course;
	@Column
	private String type;
	@Column
	private double price;
	@Column
	private String status;
	@Column
	private Date graduation;
	@Column
	private String receipt;
	@Column
	private Date date;
//	//--------------------------------------------------------------------
//	//One to one relationship
//	@JoinColumn
//	@OneToOne  //eagarly fetch - hib-te automaticly join, no need to write query
//	private RequestApproved requestA;
	
	public Request( ) {}

	public Request(int requestId, int employeeId, String school, String course, String type, double price,
			String status, Date graduation, String receipt, Date date) {
		super();
		this.requestId = requestId;
		this.employeeId = employeeId;
		this.school = school;
		this.course = course;
		this.type = type;
		this.price = price;
		this.status = status;
		this.graduation = graduation;
		this.receipt = receipt;
		this.date = date;
	}

	public int getRequestId() {
		return requestId;
	}

	public void setRequestId(int requestId) {
		this.requestId = requestId;
	}

	public int getEmployeeId() {
		return employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	public String getSchool() {
		return school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	public String getCourse() {
		return course;
	}

	public void setCourse(String course) {
		this.course = course;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getGraduation() {
		return graduation;
	}

	public void setGraduation(Date graduation) {
		this.graduation = graduation;
	}

	public String getReceipt() {
		return receipt;
	}

	public void setReceipt(String receipt) {
		this.receipt = receipt;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((course == null) ? 0 : course.hashCode());
		result = prime * result + ((date == null) ? 0 : date.hashCode());
		result = prime * result + employeeId;
		result = prime * result + ((graduation == null) ? 0 : graduation.hashCode());
		long temp;
		temp = Double.doubleToLongBits(price);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		result = prime * result + ((receipt == null) ? 0 : receipt.hashCode());
		result = prime * result + requestId;
		result = prime * result + ((school == null) ? 0 : school.hashCode());
		result = prime * result + ((status == null) ? 0 : status.hashCode());
		result = prime * result + ((type == null) ? 0 : type.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Request other = (Request) obj;
		if (course == null) {
			if (other.course != null)
				return false;
		} else if (!course.equals(other.course))
			return false;
		if (date == null) {
			if (other.date != null)
				return false;
		} else if (!date.equals(other.date))
			return false;
		if (employeeId != other.employeeId)
			return false;
		if (graduation == null) {
			if (other.graduation != null)
				return false;
		} else if (!graduation.equals(other.graduation))
			return false;
		if (Double.doubleToLongBits(price) != Double.doubleToLongBits(other.price))
			return false;
		if (receipt == null) {
			if (other.receipt != null)
				return false;
		} else if (!receipt.equals(other.receipt))
			return false;
		if (requestId != other.requestId)
			return false;
		if (school == null) {
			if (other.school != null)
				return false;
		} else if (!school.equals(other.school))
			return false;
		if (status == null) {
			if (other.status != null)
				return false;
		} else if (!status.equals(other.status))
			return false;
		if (type == null) {
			if (other.type != null)
				return false;
		} else if (!type.equals(other.type))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Request [requestId=" + requestId + ", employeeId=" + employeeId + ", school=" + school + ", course="
				+ course + ", type=" + type + ", price=" + price + ", status=" + status + ", graduation=" + graduation
				+ ", receipt=" + receipt + ", date=" + date + "]";
	}
	
	

}
